"""make post_id unique in cleaned_texts

Revision ID: edbf4b84d570
Revises: 52caa43d62de
Create Date: 2026-06-11 12:43:28.656863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edbf4b84d570'
down_revision = '52caa43d62de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaned_texts', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['post_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaned_texts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
